development: &development
  adapter: mysql2
  host: localhost
  username: root
  password:
  database: refinery_development

test: &test
  adapter: mysql2
  host: localhost
  username: root
  password:
  database: refinery_test

production: &production
  adapter: mysql2
  host: localhost
  database: refinery_production
  username: root
  password: r00t
